skeleton: add /data partition, and deploy script hooks

diff --git a/board/led-alarm/skeleton/usr/share/jlbsp/upgrade-hooks b/board/led-alarm/skeleton/usr/share/jlbsp/upgrade-hooks
--- a/board/led-alarm/skeleton/usr/share/jlbsp/upgrade-hooks
+++ b/board/led-alarm/skeleton/usr/share/jlbsp/upgrade-hooks
@@ -1,8 +1,26 @@
 #!/usr/bin/env sh
 
+data_partition=""
+
+. "/usr/share/jlbsp/data-mount"
+
 validate_led_alarm() {
-	echo "my validate $1 $2"
-	[ -b "${2}1" ] && [ -b "${2}2" ] && [ ! -b "${2}3" ] && return 0
+	[ -b "${2}1" ] || return 1
+	[ -b "${2}2" ] || return 1
+	case "$1" in
+		loop)
+			[ ! -b "${2}3" ] && return 0
+			;;
+		orig)
+			[ -b "${2}4" ] && return 1
+			if [ -b "${2}3" ]; then
+				echo "Found data partition, will preserve!"
+				data_partition="${2}3"
+			fi
+			return 0
+			;;
+	esac
+	echo "Validation of $1 device failed!"
 	return 1
 }
 
@@ -11,11 +29,35 @@ upgrade_start() {
 	validate_func="validate_led_alarm"
 }
 upgrade_pre_remount() {
-	echo "pre remount"
-}
-upgrade_pre_dd() {
-	echo "pre dd"
+	if [ -n "$data_partition" ]; then
+		echo "Stopping LED alarm clock service"
+		"/etc/init.d/S95led-alarm" stop || true
+		sleep 1.5 # led-alarm doesn't always immediately exit
+		echo "Unmounting data partition at $data_mountpoint!"
+		mountpoint -q "$data_mountpoint" && umount -f "$data_mountpoint"
+		echo "Copying data partition to RAM!"
+		echo dd "if=$data_partition" "of=/tmp/data-prt.img" "bs=4M"
+		dd "if=$data_partition" "of=/tmp/data-prt.img" "bs=4M"
+		echo "Copied data partition to RAM!"
+	fi
 }
 upgrade_post_dd() {
-	echo "post dd"
+	base="$(echo "$3" | sed 's/p[0-9]*$//g')"
+	data="${base}p3"
+
+	partprobe
+
+	if [ ! -b "${data}" ]; then
+		make_data_partition "${base}" "${data}"
+	fi
+
+	if [ -n "$data_partition" ]; then
+		if [ "$data" != "$data_partition" ]; then
+			echo "Data partition computed name (${data}) doesn't match original name (${data_partition})"
+			return 1
+		fi
+		echo dd "if=$4/tmp/data-prt.img" "of=$data_partition" "bs=4M"
+		dd "if=$4/tmp/data-prt.img" "of=$data_partition" "bs=4M"
+		echo "Data partition restored!"
+	fi
 }
